spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/codelab
    username: root
#    password: Secure@5432
    password: Password@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false

  devtools:
    restart:
      enabled: true

server:
  port: 8080
